#!/usr/bin/env bash

# Variables for MySQL database server and related.
# MYSQL_SERVER_ADDRESS and MYSQL_SERVER_PORT are defined in conf/global.
# SQL_SERVER_ADDRESS and SQL_SERVER_PORT are defined in dialog/config_via_dialog.sh.

export MYSQL_MY_CNF='/etc/my.cnf'
export MYSQL_MY_CNF_SAMPLE="${SAMPLE_DIR}/mysql/my.cnf"

export MYSQL_RC_SCRIPT_NAME='mysql'

# MySQL config file.
if [ X"${DISTRO}" == X'OPENBSD' ]; then
    export MYSQL_RC_SCRIPT_NAME='mysqld'
fi

export MYSQLD_RC_SCRIPT="${DIR_RC_SCRIPTS}/${MYSQL_RC_SCRIPT_NAME}"
export MYSQL_INIT_SQL="${RUNTIME_DIR}/mysql_init.sql"
export MYSQL_VMAIL_SQL="${RUNTIME_DIR}/mysql_vmail.sql"

# SQL structure of MySQL vmail database.
export MYSQL_VMAIL_STRUCTURE_SAMPLE="${SAMPLE_DIR}/mailbsd/mailbsd.mysql"

# File used to stores MySQL root password to avoid warning:
# "Using a password on the command line interface can be insecure."
# File will be copied to /root/.my.cnf after MailBSD installation.
# WARNING: Do NOT set it to /root/.my.cnf here.
export MYSQL_DEFAULTS_FILE_ROOT="/root/.my.cnf"
export MYSQL_CLIENT_ROOT="mysql --defaults-file=${MYSQL_DEFAULTS_FILE_ROOT}"

# Hostname or IP address used in MySQL GRANT command (allow remote access from
# this hostname/IP).
# Usually it's 'localhost', but not in FreeBSD Jail (use ${LOCAL_ADDRESS} or
# hostname of Jail instead).
if [ X"${LOCAL_ADDRESS}" == X'127.0.0.1' ]; then
    # Pre-define MYSQL_GRANT_HOST while running MailBSD to use a remote MySQL
    # server. For example:
    # MYSQL_GRANT_HOST='192.168.1.2' bash MailBSD.sh
    export MYSQL_GRANT_HOST="${MYSQL_GRANT_HOST:=localhost}"
else
    export MYSQL_GRANT_HOST="${LOCAL_ADDRESS}"
fi

# Custom settings
export MYSQL_MAX_CONNECTIONS="${MYSQL_MAX_CONNECTIONS:=1024}"