#!/usr/bin/env bash

# For SpamAssassin.

export SA_CONF_DIR='/etc/mail/spamassassin'
export SA_RULES_DIR='/usr/share/spamassassin'
export BIN_SA_UPDATE='sa-update'
export BIN_SA_COMPILE='sa-compile'
export SA_INIT_PRE="${SA_CONF_DIR}/init.pre"
export SA_LOCAL_CF="${SA_CONF_DIR}/local.cf"
export SA_PLUGIN_RAZOR_CONF="${SA_CONF_DIR}/razor.conf"