#!/usr/bin/env bash

# web servers and PHP
export HTTPD_PORT="${HTTPD_PORT:=80}"
export HTTPS_PORT="${HTTPS_PORT:=443}"

# store extra web applications
export HTTPD_SERVERROOT='/opt/www'

# Daemon user.
export HTTPD_USER='www'
export HTTPD_GROUP='www'

# Web data.
export HTTPD_DOCUMENTROOT="/var/www/htdocs"

[ X"${WEB_SERVER}" == X'NGINX' ] && . ${CONF_DIR}/nginx

. ${CONF_DIR}/php